server:
  port: 8072

spring: 
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:7080/realms/oralie/protocol/openid-connect/certs"

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
