build:
  version: "2.0"

products:
  message: "This is message for products service related QA APIs"
  contactInfo:
    name: "Viet QA"
    email: "vvivu789@gmail.com"
  onCallSupport:
    - (+84)123456789
    - (+84)123456789
