build:
  version: "1.0"

products:
  message: "This is message for products service related production APIs"
  contactInfo:
    name: "Viet Prod"
    email: "vvivu789@gmail.com"
  onCallSupport:
    - (+84)123456789
    - (+84)123456789

jwt:
  set-uri: "http://keycloak:8080/realms/oralie/protocol/openid-connect/certs"
